# Generated by Django 3.1.4 on 2021-01-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AllDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Launch_services', models.DateField(null=True)),
                ('month_Launch_services', models.DateField(null=True)),
                ('quarter_Launch_services', models.IntegerField(choices=[(1, 'I kw.'), (2, 'II kw.'), (3, 'III kw.'), (4, 'IV kw.')], null=True)),
                ('date_card_project', models.DateField(null=True)),
                ('date_agreement', models.DateField(null=True)),
                ('date_estimated_budget_order', models.DateField(null=True)),
                ('date_estimated_budget_execution', models.DateField(null=True)),
                ('date_estimated_budget_to_fill', models.DateField(null=True)),
                ('date_estimated_budget_accept', models.DateField(null=True)),
                ('date_internal_net_order', models.DateField(null=True)),
                ('date_internal_net_execution', models.DateField(null=True)),
                ('date_FO_question_of_price', models.DateField(null=True)),
                ('date_FO_answer_with_price', models.DateField(null=True)),
                ('date_FO_order', models.DateField(null=True)),
                ('date_FO_execution', models.DateField(null=True)),
                ('date_LAN_GPON_launch', models.DateField(null=True)),
                ('date_CATV_IPTV_launch', models.DateField(null=True)),
                ('date_reckoning', models.DateField(null=True)),
                ('date_expenditure_FO', models.DateField(null=True)),
                ('date_expenditure_avtive_elements', models.DateField(null=True)),
                ('date_expenditure_inactive_elements', models.DateField(null=True)),
                ('date_expenditure_sewerage', models.DateField(null=True)),
                ('date_expenditure_OLT', models.DateField(null=True)),
                ('date_expenditure_for_deweloper', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.FloatField(null=True)),
                ('amount_FO', models.FloatField(null=True)),
                ('amount_sewerage', models.FloatField(null=True)),
                ('amount_internal_network', models.FloatField(null=True)),
                ('amount_to_reckoning_budget', models.FloatField(null=True)),
                ('amount_CN_to_reckoning_budget', models.FloatField(null=True)),
                ('amount_sewerage_to_reckoning_budget', models.FloatField(null=True)),
                ('amount_per_HP_without_FO', models.FloatField(null=True)),
                ('amount_per_HP_with_FO', models.FloatField(null=True)),
                ('amount_inactive_elements', models.FloatField(null=True)),
                ('amount_active_elements', models.FloatField(null=True)),
                ('amount_activity', models.FloatField(null=True)),
                ('amount_OLT', models.FloatField(null=True)),
                ('amount_for_deweloper', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GPON_node_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_RT', models.URLField(null=True)),
                ('link_RT_FO', models.URLField(null=True)),
                ('link_KI', models.URLField(null=True)),
                ('link_SMP_osiedle', models.URLField(null=True)),
                ('link_SMP_FO', models.URLField(null=True)),
                ('link_kosztorys_ryczałtowy', models.URLField(null=True)),
                ('link_kosztorys_rozliczony', models.URLField(null=True)),
                ('link_skan_umowy', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_last_name', models.CharField(max_length=40)),
                ('job', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=64, null=True)),
                ('SM_PM_initial', models.CharField(default='MS', max_length=4)),
                ('deweloper_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.developer')),
                ('general_contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.general')),
            ],
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KI_number', models.IntegerField(null=True)),
                ('MPK_number', models.CharField(default='brak MPK', max_length=10, null=True)),
                ('MPK_number_sewerage', models.CharField(max_length=10, null=True)),
                ('building_name', models.CharField(max_length=255)),
                ('building_adres', models.CharField(max_length=255)),
                ('parcel_number', models.CharField(max_length=255, null=True)),
                ('quantity_HP', models.IntegerField(default=0)),
                ('quantity_LU', models.IntegerField(default=0)),
                ('year_Launch_services', models.IntegerField(null=True)),
                ('estimated_budget_accept', models.IntegerField(choices=[(0, 'puste'), (1, 'tak'), (2, 'nie'), (3, 'w trakcie')], null=True)),
                ('flat_price', models.FloatField(null=True)),
                ('kind_of_inhabitation', models.IntegerField(choices=[(1, 'zasiedlone'), (2, 'w trakcie'), (3, 'deweloper')], default=3, null=True)),
                ('status', models.IntegerField(choices=[(1, 'realizacja'), (2, 'eksploatacja'), (3, 'niezrealizowane'), (4, 'negocjacje'), (5, 'chcemy'), (6, 'inwestycja wstrzymana')], default=5)),
                ('services_provided', models.IntegerField(choices=[(1, 'GPON/IPTV'), (2, 'GPON/CATV'), (3, 'LAN/CATV'), (4, 'LAN')], default=1)),
                ('internal_net_property', models.IntegerField(choices=[(1, 'SM'), (2, 'SM/JMDI'), (3, 'SM/UPC'), (4, 'SM/UPC/ Vectra'), (5, 'SM/Wspólnota'), (6, 'Wspólnota'), (7, 'bd')], default=7)),
                ('remarks_of_MS', models.TextField(null=True)),
                ('remarks_of_AK', models.TextField(null=True)),
                ('GPON_node_localisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.gpon_node_list')),
                ('competitors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.competitors')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.developer')),
                ('range_of_activity', models.ManyToManyField(to='residentials.Activities')),
            ],
        ),
    ]
