# Generated by Django 3.1.4 on 2021-01-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='parcel_number',
        ),
        migrations.AlterField(
            model_name='buildings',
            name='MPK_number_sewerage',
            field=models.CharField(default='brak MPK', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='estimated_budget_accept',
            field=models.IntegerField(choices=[(0, 'puste'), (1, 'tak'), (2, 'nie'), (3, 'w trakcie')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='range_of_activity',
            field=models.ManyToManyField(null=True, to='residentials.Activities'),
        ),
    ]
