# Generated by Django 3.1.4 on 2020-12-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='deweloper_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.developer'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='general_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.general'),
        ),
    ]
