# Generated by Django 3.1.4 on 2021-01-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0002_auto_20210106_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='competitors',
            field=models.ForeignKey(default='bd', null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.competitors'),
        ),
    ]
