# Generated by Django 3.1.4 on 2021-01-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0003_auto_20210106_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildings',
            name='range_of_activity',
        ),
        migrations.AddField(
            model_name='buildings',
            name='range_of_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.activities'),
        ),
    ]
