# Generated by Django 3.1.4 on 2020-12-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0003_auto_20201213_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='competitors',
            field=models.ManyToManyField(to='residentials.Competitors'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='range_of_activity',
            field=models.ManyToManyField(to='residentials.Activities'),
        ),
    ]
