# Generated by Django 3.1.4 on 2020-12-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0004_auto_20201213_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitors',
            old_name='Jmdi',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='competitors',
            name='MetroInternet',
        ),
        migrations.RemoveField(
            model_name='competitors',
            name='Netia',
        ),
        migrations.RemoveField(
            model_name='competitors',
            name='Opl',
        ),
        migrations.RemoveField(
            model_name='competitors',
            name='Other',
        ),
        migrations.RemoveField(
            model_name='competitors',
            name='Upc',
        ),
        migrations.RemoveField(
            model_name='competitors',
            name='Vectra',
        ),

    ]
