# Generated by Django 3.1.4 on 2021-01-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0004_auto_20210106_1610'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buildings',
            table='residential_area',
        ),
    ]
