# Generated by Django 3.1.4 on 2020-12-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0005_auto_20201215_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='name',
            field=models.CharField(default='bd', max_length=64),
        ),
        migrations.AddField(
            model_name='general',
            name='name',
            field=models.CharField(default='bd', max_length=64),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='KI_number',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='MPK_number',
            field=models.CharField(default='bd', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='MPK_number_sewerage',
            field=models.CharField(default='bd', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='estimated_budget_accept',
            field=models.IntegerField(choices=[(0, 'puste'), (1, 'yes'), (2, 'no'), (3, 'in progress')], default=0),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='flat_price',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='internal_net_property',
            field=models.IntegerField(choices=[(1, 'SM'), (2, 'SM/JMDI'), (3, 'SM/UPC'), (4, 'SM/UPC/ Vectra'), (5, 'SM/Wspólnota'), (6, 'Wspólnota'), (7, 'bd')], default='7'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='parcel_number',
            field=models.CharField(default='bd', max_length=255),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='quantity_HP',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='quantity_LU',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='remarks_of_AK',
            field=models.TextField(default='bd'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='remarks_of_MS',
            field=models.TextField(default='bd'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='SM_PM_initial',
            field=models.CharField(default='MS', max_length=4),
        ),
        migrations.AlterField(
            model_name='persons',
            name='deweloper_company',
            field=models.ForeignKey(default='bd', on_delete=django.db.models.deletion.CASCADE, to='residentials.developer'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='email',
            field=models.CharField(default='bd', max_length=64),
        ),
        migrations.AlterField(
            model_name='persons',
            name='general_contractor',
            field=models.ForeignKey(default='bd', on_delete=django.db.models.deletion.CASCADE, to='residentials.general'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
    ]
