# Generated by Django 3.1.4 on 2020-12-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0007_auto_20201218_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='quantity_HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='quantity_LU',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persons',
            name='deweloper_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentials.developer'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='general_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentials.general'),
        ),
    ]
