# Generated by Django 3.1.4 on 2020-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0009_auto_20201218_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='backbone_catv',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='backbone_ftth',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='backbone_lan',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='ftth_100_percent',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='ftth_reserves',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='mast_radio',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='money_to_deweloper',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='rg6_100_percent',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='rg6_30_percent',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='rg6_33_percent',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='rg6_50_percent',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='rg6_zit_100_percent',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='sewerage',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='utp_100_percent',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='utp_reserves_50_percent',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='zit',
        ),
        migrations.AddField(
            model_name='activities',
            name='scope',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='competitors',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='general',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
