# Generated by Django 3.1.4 on 2020-12-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0010_auto_20201219_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='deweloper_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.developer'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='general_contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentials.general'),
        ),
    ]
