# Generated by Django 3.1.4 on 2020-12-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0011_auto_20201219_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='KI_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='MPK_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='MPK_number_sewerage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='estimated_budget_accept',
            field=models.IntegerField(choices=[(0, 'puste'), (1, 'yes'), (2, 'no'), (3, 'in progress')], null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='flat_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='parcel_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='remarks_of_AK',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='remarks_of_MS',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
