# Generated by Django 3.1.4 on 2020-12-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0012_auto_20201221_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='kind_of_inhabitation',
            field=models.IntegerField(choices=[(1, 'zasiedlone'), (2, 'w trakcie'), (3, 'deweloper')], default=3),
        ),
    ]
