# Generated by Django 3.1.4 on 2020-12-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentials', '0013_auto_20201221_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildings',
            name='KI_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='kind_of_inhabitation',
            field=models.IntegerField(choices=[(1, 'zasiedlone'), (2, 'w trakcie'), (3, 'deweloper')], default=3, null=True),
        ),
    ]
